ALTER TABLE revlog
ADD COLUMN mod INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE revlog
ADD COLUMN feedback TEXT DEFAULT "" NOT NULL;
ALTER TABLE revlog
ADD COLUMN tags TEXT DEFAULT "" NOT NULL;
UPDATE col
SET extended_version = 202212011756;